#include "ap.h"
#include "vga.h"
#include "timer.h"
#include "power/cstate.h"

/* Embedded trampoline binary (generated by build.ps1) */
extern char _binary_ap_trampoline_bin_start[];
extern char _binary_ap_trampoline_bin_end[];
extern char _binary_ap_trampoline_bin_size[];

/* BSP 的 PML4 页表基址 (定义在 boot.S 的 .data 段) */
extern uint64_t pml4[];

/* AP 入口函数 (声明在 kmain.c) */
extern void ap_entry(int apic_id);

/* 为每个 AP 分配的栈空间 */
static uint8_t ap_stacks[MAX_CORES][8192] __attribute__((aligned(16)));

static int ap_cores_online = 1;  /* BSP counts as 1 */
static int ap_apic_ids[MAX_CORES];
static int ap_apic_count = 0;

/* AP power state tracking */
static int ap_core_states[MAX_CORES];  /* CSTATE_ACTIVE/C1E/DEEP */
static uint64_t ap_idle_since_ms[MAX_CORES];

/* Print unsigned int helper */
static void print_uint2(uint64_t n) {
    if (n == 0) { vga_putc('0'); return; }
    char rev[32]; int rp = 0;
    while (n) { rev[rp++] = '0' + (n % 10); n /= 10; }
    while (rp) vga_putc(rev[--rp]);
}

/* Read a 32-bit LAPIC register */
static uint32_t lapic_read(uint32_t reg) {
    volatile uint32_t* ptr = (volatile uint32_t*)(uint64_t)(LAPIC_BASE + reg);
    return *ptr;
}

/* Write a 32-bit LAPIC register */
static void lapic_write(uint32_t reg, uint32_t val) {
    volatile uint32_t* ptr = (volatile uint32_t*)(uint64_t)(LAPIC_BASE + reg);
    *ptr = val;
}

/* Wait for LAPIC ICR delivery (poll bit 12 = Delivery Status) */
static void lapic_wait_icr(void) {
    while (lapic_read(0x300) & (1 << 12)) {
        __asm__ volatile("pause");
    }
}

/* Send IPI to a specific APIC ID */
static void lapic_send_ipi(uint32_t apic_id, uint32_t vector, uint32_t delivery_mode, int level) {
    /* ICR high: APIC ID in bits 24-27 */
    uint32_t icr_high = apic_id << 24;
    lapic_write(0x310, icr_high);

    /* ICR low: vector + delivery mode + physical destination (bit 11 = 0) */
    uint32_t icr_low = vector | (delivery_mode << 8);
    if (level) {
        icr_low |= (1 << 14);  /* Level = Assert (for INIT) */
        icr_low |= (1 << 15);  /* Trigger Mode = Level */
    }
    /* For SIPI: level=0, so bits 14/15 are 0 => edge-triggered, correct */
    lapic_write(0x300, icr_low);

    lapic_wait_icr();
}

/* Send INIT IPI */
static void lapic_send_init(uint32_t apic_id) {
    /* INIT: delivery mode 5, level-triggered, assert */
    lapic_send_ipi(apic_id, 0, 5, 1);
    /* De-assert */
    lapic_write(0x310, apic_id << 24);
    lapic_write(0x300, 0x00008500);
    lapic_wait_icr();
}

/* Send SIPI (Startup IPI) */
static void lapic_send_sipi(uint32_t apic_id, uint8_t vector) {
    /* Startup: delivery mode 6, edge-triggered */
    lapic_send_ipi(apic_id, vector, 6, 0);
}

void ap_init(void) {
    ap_cores_online = 1;
    ap_apic_count = 0;

    /* Check and enable LAPIC */
    uint64_t apic_base = rdmsr(0x1B);
    if (!(apic_base & (1ULL << 11))) {
        apic_base |= (1ULL << 11);  /* APIC Global Enable */
        wrmsr(0x1B, apic_base);
    }
    if (apic_base & (1ULL << 10)) {
        apic_base &= ~(1ULL << 10); /* x2APIC -> xAPIC */
        wrmsr(0x1B, apic_base);
    }

    /* Enable LAPIC: set software enable bit */
    uint32_t svr = lapic_read(0x0F0);
    lapic_write(0x0F0, svr | 0x1FF);  /* Enable + spurious vector 0xFF */

    /* Set Task Priority to 0 */
    lapic_write(0x080, 0);

    /* Read BSP LAPIC ID */
    uint32_t lapic_id = (lapic_read(0x20) >> 24) & 0xFF;
    ap_apic_ids[ap_apic_count++] = (int)lapic_id;
}

void ap_start_all(void) {
    /* 获取 trampoline 大小 */
    uint64_t tramp_size = (uint64_t)(uint64_t)_binary_ap_trampoline_bin_size;

    if (tramp_size == 0 || tramp_size > 0xF00) {
        vga_puts("[AP] Trampoline size invalid, skipping\n");
        return;
    }

    /* 获取 PML4 物理地址 */
    uint64_t pml4_phys = (uint64_t)(uint64_t)&pml4[0];

    /* 复制 trampoline 到 0x8000 */
    uint8_t* tramp_dst = (uint8_t*)(uint64_t)AP_TRAMPOLINE_ADDR;
    uint8_t* tramp_src = (uint8_t*)_binary_ap_trampoline_bin_start;
    for (uint64_t i = 0; i < tramp_size; i++) {
        tramp_dst[i] = tramp_src[i];
    }

    /* 填充数据区 */
    volatile uint64_t* data = (volatile uint64_t*)(uint64_t)(AP_TRAMPOLINE_ADDR + 0xF00);
    data[0] = pml4_phys;                        /* DATA_PML4 */
    data[1] = (uint64_t)(uint64_t)&ap_entry;    /* DATA_ENTRY */
    data[2] = (uint64_t)(uint64_t)&ap_stacks[0][8192]; /* DATA_STACK (will be updated per AP) */
    data[3] = 0;                                /* DATA_APIC_ID (will be updated per AP) */

    vga_puts("[AP] Starting AP cores...\n");

    /* 启动每个 AP (跳过 BSP 的 APIC ID) */
    int bsp_apic_id = ap_apic_ids[0];
    int ap_index = 1; /* AP 栈索引 */

    for (int apic_id = 0; apic_id < MAX_CORES; apic_id++) {
        if (apic_id == bsp_apic_id) continue;
        if (ap_index >= MAX_CORES) break;

        /* 更新数据区: 栈和 APIC ID */
        data[2] = (uint64_t)(uint64_t)&ap_stacks[ap_index][8192];
        data[3] = (uint64_t)apic_id;

        vga_puts("[AP] Waking APIC ID ");
        print_uint2((uint64_t)apic_id);
        vga_puts("...\n");

        /* INIT-SIPI-SIPI 序列 */
        lapic_send_init((uint32_t)apic_id);
        timer_mdelay(10); /* 等待 10ms */

        lapic_send_sipi((uint32_t)apic_id, (uint8_t)(AP_TRAMPOLINE_ADDR >> 12));
        timer_mdelay(1); /* 等待 200us (实际用 1ms 简化) */

        lapic_send_sipi((uint32_t)apic_id, (uint8_t)(AP_TRAMPOLINE_ADDR >> 12));

        /* 等待 AP 启动 (最多 200ms) */
        int timeout = 200;
        while (timeout > 0 && ap_cores_online <= ap_index) {
            timer_mdelay(1);
            timeout--;
        }

        if (ap_cores_online > ap_index) {
            ap_apic_ids[ap_apic_count++] = apic_id;
            vga_puts("[AP] Core ");
            print_uint2((uint64_t)apic_id);
            vga_puts(" online!\n");
            ap_index++;
        } else {
            vga_puts("[AP] Core ");
            print_uint2((uint64_t)apic_id);
            vga_puts(" failed to start\n");
        }
    }

    vga_puts("[AP] Done. ");
    print_uint2((uint64_t)ap_cores_online);
    vga_puts(" cores online\n");
}

int ap_get_core_id(void) {
    uint32_t id = (lapic_read(0x20) >> 24) & 0xFF;
    return (int)id;
}

int ap_online_count(void) {
    return ap_cores_online;
}

int ap_get_state(int core_idx) {
    if (core_idx < 0 || core_idx >= MAX_CORES) return CSTATE_ACTIVE;
    if (core_idx >= ap_cores_online) return CSTATE_DEEP;  /* Not online = deep */
    return ap_core_states[core_idx];
}

void ap_set_state(int core_idx, int state) {
    if (core_idx < 0 || core_idx >= MAX_CORES) return;
    ap_core_states[core_idx] = state;
}

/* 由 AP trampoline 调用的入口点 */
void ap_core_online(int apic_id) {
    ap_cores_online++;
    ap_apic_ids[ap_apic_count++] = apic_id;
    /* Initialize power state for this core */
    int idx = ap_cores_online - 1;
    if (idx < MAX_CORES) {
        ap_core_states[idx] = CSTATE_ACTIVE;
        ap_idle_since_ms[idx] = 0;
    }
}